services:
  db:
    image: mysql
    restart: always

    command: --default-authentication-plugin=mysql_native_password

    environment:
      - MYSQL_ROOT_PASSWORD=zumbazumba

    ports:
      - 3306:3306
      