services:
  taiyouServer:
    image: mysql
    container_name: mysql_container

    command: --default-authentication-plugin=mysql_native_password

    ports:
      - 3306:3306

    environment:
      - MYSQL_ROOT_PASSWORD=zumbazumba

    